const body = document.getElementById("body");
body.style.visibility = "hidden";
const Pnameon1 = localStorage.getItem("names1");
const Pnameon2 = localStorage.getItem("names2");
const PMm = [0,1,2,3,4,5];
PMm[0] = JSON.parse(localStorage.getItem("PK1"));
PMm[1] = JSON.parse(localStorage.getItem("PK2"));
PMm[2] = JSON.parse(localStorage.getItem("PK3"));
PMm[3] = JSON.parse(localStorage.getItem("PK4"));
PMm[4] = JSON.parse(localStorage.getItem("PK5"));
PMm[5] = JSON.parse(localStorage.getItem("PK6"));
let PM = PMm.map(v => ({...v}));
let audio1;
let audio2;
let PK1;
let PK2;
let status1;
let status2;
let namedp1;
let namedp2;
let type11;
let type12;
let type21;
let type22;
let ARdp1;
let BRdp1;
let CRdp1;
let DRdp1;
let SRdp1;
let ARdp2;
let BRdp2;
let CRdp2;
let DRdp2;
let SRdp2;
let dps1;
let dps2;
let Lv1;
let Lv2;
let name1;
let name2;
let HPdp1;
let HPdp2;
let MHPdp1;
let MHPdp2;
let attack1;
let attack2;
let change1;
let change2;
let Adp1;
let Adp2;
let Cdp1;
let Cdp2;
let subPK1;
let subPK2;
let subPK3;
let subPK4;
let subPK5;
let subPK6;
let skill11;
let skill12;
let skill13;
let skill14;
let skill21;
let skill22;
let skill23;
let skill24;
let skill11dp;
let skill12dp;
let skill13dp;
let skill14dp;
let skill21dp;
let skill22dp;
let skill23dp;
let skill24dp;
let PN1;
let PKpic1;
let PKname1;
let F1;
let Fdp11;
let Fdp12;
let skiller;
let skilltype;
let bodytype1;
let bodytype2;
let bodytype11;
let bodytype12;
let bodytype21;
let bodytype22;
let PN2;
let PKpic2;
let PKname2;
let F2;
let Fdp21;
let Fdp22;
let skiller1;
let skiller2;
let healeder1;
let healeder2;
let MGdp1;
let MGdp2;
let MG1;
let MG2;
let MA1;
let MA2;
let MAXdp1;
let MAXdp2;
let MAX1;
let MAX2;
let weather = "cansel";
let field = "cansel";
let voice = 1;
let vitalpt = 0;
let plushit1 = 0;
let plushit2 = 0;
let dmg = 5;
let AR1 = 6;
let BR1 = 6;
let CR1 = 6;
let DR1 = 6;
let SR1 = 6;
let AR2 = 6;
let BR2 = 6;
let CR2 = 6;
let DR2 = 6;
let SR2 = 6;
let chaos = 0;
let ID1 = 10;
let ID2 = 10;
let minus = 0;
let bothchange = 0;
let firsted = 0;
let dies1 = 0;
let dies2 = 0;
let diept1 = 3;
let diept2 = 3;
let shields = 0;
let WApt = 0;
let pt1 = 0;
let pt2 = 0;
let windpt1 = 0;
let windpt2 = 0;
let healID1 = 0;
let healID2 = 0;
let windrate1 = 1;
let windrate2 = 1;
let unspeedpt = 0;
let weatherpt = 0;
let fieldpt = 0;
let MAXpt1 = 0;
let MAXpt2 = 0;
let futurehp1 = 0;
let futurehp2 = 0;
let PBpt1 = 0;
let SBpt1 = 0;
let OBpt1 = 0;
let PBpt2 = 0;
let SBpt2 = 0;
let OBpt2 = 0;
let shieldpt1 = 0;
let shieldpt2 = 0;
let blessing = 1;
let nosongpt1 = 0;
let nosongpt2 = 0;
let abnormal1 = "unknown";
let abnormal2 = "unknown";
let audioed1 = false;
let audioed2 = false;
let attackstorage1 = false;
let attackstorage2 = false;
let changestorage1 = false;
let changestorage2 = false;
let skill1 = false;
let changer1 = false;
let skill2 = false;
let changer2 = false;
let nodmg = false;
let first = false;
let down1 = false;
let down2 = false;
let chaosdp = false;
let wince1 = false;
let wince2 = false;
let heal1 = false;
let heal2 = false;
let healdp1 = false;
let healdp2 = false;
let highhitrate = false;
let hyperhitrate = false;
let breakarmor = false;
let breakarmored1 = false;
let breakarmored2 = false;
let BA1 = false;
let BA2 = false;
let AH = false;
let afterback1 = false;
let afterback2 = false;
let heatchange = false;
let HC1 = false;
let HC2 = false;
let CR1h1 = false;
let CR1h2 = false;
let Wattack = false;
let Wattacked = false;
let clearbody = false;
let CB1 = false;
let CB2 = false;
let backwind1 = false;
let backwind2 = false;
let suicide1 = false;
let suicide2 = false;
let recoil1 = false;
let recoil2 = false;
let flying1 = false;
let flying2 = false;
let againheal1 = false;
let againheal2 = false;
let MGstart1 = false;
let MGstart2 = false;
let MGed1 = false;
let MGed2 = false;
let MAXstart1 = false;
let MAXstart2 = false;
let MAXed1 = false;
let MAXed2 = false;
let formed1 = false;
let formed2 = false;
let resist = false;
let RE1 = false;
let RE2 = false;
let transform1 = false;
let transform2 = false;
let Fdown1 = false;
let Fdown2 = false;
let startdash1 = false;
let startdash2 = false;
let unspeed = false;
let fishes1 = false;
let fishes2 = false;
let scatter = false;
let AR1five1 = false;
let AR1five2 = false;
let snowdown1 = false;
let snowdown2 = false;
let illusion1 = false;
let illusion2 = false;
let vision1 = false;
let vision2 = false;
let sturdy1 = false;
let sturdy2 = false;
let weather1 = false;
let weather2 = false;
let sunny = false;
let rainy = false;
let sandstrom = false;
let snowy = false;
let field1 = false;
let field2 = false;
let phycho = false;
let elec = false;
let mist = false;
let grass = false;
let shield1 = false;
let shield2 = false;
let MAXshield1 = false;
let MAXshield2 = false;
let shielddp1 = false;
let shielddp2 = false;
let onekilloff1 = false;
let onekilloff2 = false;
let firster1 = false;
let firster2 = false;
let skyoff1 = false;
let skyoff2 = false;
let nochaos = false;
let Pbarrier1 = false;
let Pbarrier2 = false;
let Sbarrier1 = false;
let Sbarrier2 = false;
let Obarrier1 = false;
let Obarrier2 = false;
let PBed = false;
let SBed = false;
let OBed = false;
let breakPB1 = false;
let breakPB2 = false;
let breakSB1 = false;
let breakSB2 = false;
let breakOB1 = false;
let breakOB2 = false;
let PBing1 = false;
let PBing2 = false;
let SBing1 = false;
let SBing2 = false;
let OBing1 = false;
let OBing2 = false;
let reaction1 = false;
let reaction2 = false;
let outskin = false;
let drum = false;
let secondattack1 = false;
let secondattack2 = false;
let smog = false;
let dier1 = false;
let dier2 = false;
let speeder1 = false;
let speeder2 = false;
let AH2 = false;
let AMH = false;
let noattack = false;
let noA1 = false;
let noA2 = false;
let nosong1 = false;
let nosong2 = false;
let noAdown = false;
let notAdown = false;
let daruma = false;
let twicevoice = false;

window.onload = function() {
 setTimeout(start1,50);
};
function start1() {
 alert("さぁ始まりましたポケモンバトル");
 alert("両者負けずに頑張りましょう！");
 audio1 = document.getElementById("audio1");
 audio2 = document.getElementById("audio2");
 PK1 = document.getElementById("PK1");
 PK2 = document.getElementById("PK2");
 status1 = document.getElementById("status1");
 status2 = document.getElementById("status2");
 dps1 = document.getElementById("dp1");
 dps2 = document.getElementById("dp2");
 Lv1 = document.getElementById("Lv1");
 Lv2 = document.getElementById("Lv2");
 name1 = document.getElementById("name1");
 name2 = document.getElementById("name2");
 namedp1 = document.getElementById("namedp1");
 namedp2 = document.getElementById("namedp2");
 type11 = document.getElementById("type11");
 type12 = document.getElementById("type12");
 type21 = document.getElementById("type21");
 type22 = document.getElementById("type22");
 ARdp1 = document.getElementById("ARdp1");
 BRdp1 = document.getElementById("BRdp1");
 CRdp1 = document.getElementById("CRdp1");
 DRdp1 = document.getElementById("DRdp1");
 SRdp1 = document.getElementById("SRdp1");
 ARdp2 = document.getElementById("ARdp2");
 BRdp2 = document.getElementById("BRdp2");
 CRdp2 = document.getElementById("CRdp2");
 DRdp2 = document.getElementById("DRdp2");
 SRdp2 = document.getElementById("SRdp2");
 HPdp1 = document.getElementById("HP1");
 HPdp2 = document.getElementById("HP2");
 MHPdp1 = document.getElementById("MHP1");
 MHPdp2 = document.getElementById("MHP2");
 attack1 = document.getElementById("attack1");
 attack2 = document.getElementById("attack2");
 change1 = document.getElementById("change1");
 change2 = document.getElementById("change2");
 Adp1 = document.getElementById("Adp1");
 Adp2 = document.getElementById("Adp2");
 Cdp1 = document.getElementById("Cdp1");
 Cdp2 = document.getElementById("Cdp2");
 skill11 = document.getElementById("skill11");
 skill12 = document.getElementById("skill12");
 skill13 = document.getElementById("skill13");
 skill14 = document.getElementById("skill14");
 skill21 = document.getElementById("skill21");
 skill22 = document.getElementById("skill22");
 skill23 = document.getElementById("skill23");
 skill24 = document.getElementById("skill24");
 skill11dp = document.getElementById("skill11dp");
 skill12dp = document.getElementById("skill12dp");
 skill13dp = document.getElementById("skill13dp");
 skill14dp = document.getElementById("skill14dp");
 skill21dp = document.getElementById("skill21dp");
 skill22dp = document.getElementById("skill22dp");
 skill23dp = document.getElementById("skill23dp");
 skill24dp = document.getElementById("skill24dp");
 subPK1 = document.getElementById("subPK1");
 subPK2 = document.getElementById("subPK2");
 subPK3 = document.getElementById("subPK3");
 subPK4 = document.getElementById("subPK4");
 subPK5 = document.getElementById("subPK5");
 subPK6 = document.getElementById("subPK6");
 Fdp11 = document.getElementById("Fdp11");
 Fdp12 = document.getElementById("Fdp12");
 Fdp21 = document.getElementById("Fdp21");
 Fdp22 = document.getElementById("Fdp22");
 MGdp1 = document.getElementById("MGdp1");
 MGdp2 = document.getElementById("MGdp2");
 MG1 = document.getElementById("MG1");
 MG2 = document.getElementById("MG2");
 MA1 = document.getElementById("MA1");
 MA2 = document.getElementById("MA2");
 MAXdp1 = document.getElementById("MAXdp1");
 MAXdp2 = document.getElementById("MAXdp2");
 MAX1 = document.getElementById("MAX1");
 MAX2 = document.getElementById("MAX2");
 audio1.src = "ポケモン戦闘bgm1.m4a";
 audio1.load();
 audio1.loop = true;
 audio2.src = "ポケモン戦闘bgm2.m4a";
 audio2.load();
 audio2.loop = true;
 MGdp1.style.visibility = "hidden";
 MGdp2.style.visibility = "hidden";
 MAXdp1.style.visibility = "hidden";
 MAXdp2.style.visibility = "hidden";
 PK1.style.width = 200;
 PK1.src = PM[0].img1;
 PK2.style.width = 200;
 PK2.src = PM[3].img2;
 Lv1.innerHTML = PM[0].level;
 Lv2.innerHTML = PM[3].level;
 name1.innerHTML = PM[0].name;
 PN1 = PM[0].name;
 name2.innerHTML = PM[3].name;
 PN2 = PM[3].name;
 HPdp1.innerHTML = PM[0].HP;
 HPdp2.innerHTML = PM[3].HP;
 MHPdp1.innerHTML = PM[0].MHP;
 MHPdp2.innerHTML = PM[3].MHP;
 subPK1.style.width = 150;
 subPK2.style.width = 150;
 subPK3.style.width = 150;
 subPK4.style.width = 150;
 subPK5.style.width = 150;
 subPK6.style.width = 150;
 subPK1.src = PM[0].img;
 subPK2.src = PM[1].img;
 subPK3.src = PM[2].img;
 subPK4.src = PM[3].img;
 subPK5.src = PM[4].img;
 subPK6.src = PM[5].img;
 Fdp11.style.visibility = "hidden";
 Fdp12.style.visibility = "hidden";
 Fdp21.style.visibility = "hidden";
 Fdp22.style.visibility = "hidden";
 MA1.style.visibility = "hidden";
 MA2.style.visibility = "hidden";
 ID1 = 0;
 F1 = PM[0].F;
 Fdp11.innerHTML = PM[0].name + "の";
 Fdp12.innerHTML = PM[0].F;
 ID2 = 3;
 F2 = PM[3].F;
 Fdp21.innerHTML = PM[3].name + "の";
 Fdp22.innerHTML = PM[3].F;
 skill11dp.innerHTML = skill[PM[0].skill1].name;
 skill12dp.innerHTML = skill[PM[0].skill2].name;
 skill13dp.innerHTML = skill[PM[0].skill3].name;
 skill14dp.innerHTML = skill[PM[0].skill4].name;
 skill21dp.innerHTML = skill[PM[3].skill1].name;
 skill22dp.innerHTML = skill[PM[3].skill2].name;
 skill23dp.innerHTML = skill[PM[3].skill3].name;
 skill24dp.innerHTML = skill[PM[3].skill4].name;
 skill11.style.backgroundColor = skill[PM[0].skill1].color;
 skill12.style.backgroundColor = skill[PM[0].skill2].color;
 skill13.style.backgroundColor = skill[PM[0].skill3].color;
 skill14.style.backgroundColor = skill[PM[0].skill4].color;
 skill21.style.backgroundColor = skill[PM[3].skill1].color;
 skill22.style.backgroundColor = skill[PM[3].skill2].color;
 skill23.style.backgroundColor = skill[PM[3].skill3].color;
 skill24.style.backgroundColor = skill[PM[3].skill4].color;
 skillclose1();
 skillclose2();
 changeclose1();
 changeclose2();
 PK1.style.visibility = "hidden";
 PK2.style.visibility = "hidden";
 attack1.style.visibility = "hidden";
 change1.style.visibility = "hidden";
 attack2.style.visibility = "hidden";
 change2.style.visibility = "hidden";
 dps1.style.visibility = "hidden";
 dps2.style.visibility = "hidden";
 dps1.style.backgroundColor = "#F9F9F6";
 dps2.style.backgroundColor = "#F9F9F6";
 namedp1.innerHTML = PM[0].name;
 namedp2.innerHTML = PM[3].name;
 type11.innerHTML = PM[0].bodytype1;
 type12.innerHTML = PM[0].bodytype2;
 type21.innerHTML = PM[3].bodytype1;
 type22.innerHTML = PM[3].bodytype2;
 type11.style.backgroundColor = PM[0].color1;
 type12.style.backgroundColor = PM[0].color2;
 type21.style.backgroundColor = PM[3].color1;
 type22.style.backgroundColor = PM[3].color2;
 substart();
}
function start2() {
 alert(Pnameon1 + "は" + PN1 + "を繰り出した！");
 PK1.style.visibility = "visible";
 dps1.style.visibility = "visible";
 setTimeout(start3,100);
}
function start3() {
 alert(Pnameon2 + "は" + PN2 + "を繰り出した！");
 PK2.style.visibility = "visible";
 dps2.style.visibility = "visible";
 setTimeout(start4,100);
}
function start4() {
 if (F1 === "ぎょぐん") {
  fishes1 = true;
  startdash1 = true;
  Fdp11.style.visibility = "visible";
  Fdp12.style.visibility = "visible";
  setTimeout(plus1,50);
 } else {
  if (F1 === "いかく") {
   Fdown1 = true;
   startdash1 = true;
   Fdp11.style.visibility = "visible";
   Fdp12.style.visibility = "visible";
   setTimeout(plus1,50);
  } else {
   if (F1 === "エレキメイカー" || F1 === "サイコメイカー" || F1 === "ミストメイカー") {
    field1 = true;
    startdash1 = true;
    Fdp11.style.visibility = "visible";
    Fdp12.style.visibility = "visible";
    setTimeout(plus1,50);
   } else {
    if (F1 === "すなおこし") {
     weather1 = true;
     startdash1 = true;
     Fdp11.style.visibility = "visible";
     Fdp12.style.visibility = "visible";
     setTimeout(plus1,50);
    } else {
     setTimeout(start5,250);
    };
   };
  };
 };
}
function start5() {
 if (F2 === "ぎょぐん") {
  fishes2 = true;
  startdash2 = true;
  Fdp21.style.visibility = "visible";
  Fdp22.style.visibility = "visible";
  setTimeout(plus2,50);
 } else {
  if (F2 === "いかく") {
   Fdown2 = true;
   startdash2 = true;
   Fdp21.style.visibility = "visible";
   Fdp22.style.visibility = "visible";
   setTimeout(plus2,50);
  } else {
   if ((F2 === "エレキメイカー" && field !== "elec") || (F2 === "サイコメイカー" && field !== "phycho") || (F2 === "ミストメイカー" && field !== "mist")) {
    field2 = true;
    startdash2 = true;
    Fdp21.style.visibility = "visible";
    Fdp22.style.visibility = "visible";
    setTimeout(plus2,50);
   } else {
    if (F2 === "すなおこし" && weather !== "sandstrom") {
     weather2 = true;
     startdash2 = true;
     Fdp21.style.visibility = "visible";
     Fdp22.style.visibility = "visible";
     setTimeout(plus2,50);
    } else {
     setTimeout(start6,250);
    };
   };
  };
 };
}
function start6() {
 alert("バトルスタート！");
 startdash1 = false;
 startdash2 = false;
 attack1.style.visibility = "visible";
 change1.style.visibility = "visible";
 ARdp1.innerHTML = rank[AR1].dp;
 BRdp1.innerHTML = rank[BR1].dp;
 CRdp1.innerHTML = rank[CR1].dp;
 DRdp1.innerHTML = rank[DR1].dp;
 SRdp1.innerHTML = rank[SR1].dp;
 ARdp2.innerHTML = rank[AR2].dp;
 BRdp2.innerHTML = rank[BR2].dp;
 CRdp2.innerHTML = rank[CR2].dp;
 DRdp2.innerHTML = rank[DR2].dp;
 SRdp2.innerHTML = rank[SR2].dp;
}